### ISSUE TITLE
next mockResponse read previous object

### ISSUE THREAD

**Issue by Kepro** [jefflau/jest-fetch-mock#10]
if I have

````
it('test on 404', () => {
fetch.mockResponse('Not found', { status: 404 });
}

it('test on change', () => {
fetch.mockResponse('another content');
}
````

on second mock i get also status 404... if i change it to 
```` fetch.mockResponse(testContent, { status: 200 }); ```` then it's working

**Comment by kwelch** [comment]
Does it work different if you use `mockResponseOnce`?

**Comment by Kepro** [comment]
same issue with mockResponseOnce

**Comment by kwelch** [comment]
I am clearing before each test. This should resolve this issue. 

Snippet:
```
var mockFetch;

jest.mock('node-fetch', () => {
  mockFetch = require('jest-fetch-mock');
  // set default response
  mockFetch.mockResponse(JSON.stringify({}));
  return mockFetch;
});

describe('callApi', () => {
  beforeEach(() => {
    mockFetch.mockClear();
  });
```

**Comment by jefflau** [comment]
Merged @hellatan's pull request which adds a new method to the API to clear the mocks
