### ISSUE TITLE
TypeScript integration not working

### ISSUE THREAD

**Issue by yordis** [jefflau/jest-fetch-mock#110]
I am not sure what I am doing wrong since I following the documentation

```ts
// setupFiles

import { GlobalWithFetchMock } from 'jest-fetch-mock';

const customGlobal: GlobalWithFetchMock = global as GlobalWithFetchMock;

customGlobal.fetch = require('jest-fetch-mock');

customGlobal.fetchMock = customGlobal.fetch;

```

tests
```ts
afterEach(() => {
    fetchMock.resetMocks(); // Cannot find name 'fetchMock'
  });
```

it keeps saying `Cannot find name 'fetchMock' TS2304`

**Comment by vspedr** [comment]
@yordis I'm running into the same issue, how did you solve this?

**Comment by yordis** [comment]
Setup: https://github.com/straw-hat-team/fetcher/blob/master/src/__tests__/setupFiles.ts
Usage: https://github.com/straw-hat-team/fetcher/blob/228ce7826a6ed3c2233ee04e85705eefee379e7c/src/fetcher.test.ts#L14

**Comment by viT-1** [comment]
@yordis These links aren't available =(

**Comment by yordis** [comment]
@viT-1 let me fix it, I am so sorry

**Comment by viT-1** [comment]
just found another setup configuration:
in jest setup file:
`require('jest-fetch-mock').enableMocks();`

in test:
```
import { FetchMock } from 'jest-fetch-mock';
const fetchMock = fetch as FetchMock;
```

**Comment by yinzara** [comment]
Your "in test" part isn't actually necessary though it will fix the issue.

As stated in the README, if you have an issue with "fetchMock" not being found, add a "global.d.ts" file with the text `import "jest-fetch-mock"`.  That should allow all your tests to reference the "fetchMock" global variable without adding that snippet.

**Comment by viT-1** [comment]
@yinzara 
Quoted from [here](https://stackoverflow.com/questions/42233987/how-to-configure-custom-global-interfaces-d-ts-files-for-typescript#answer-42257742)
> "Magically available interfaces" or global types is highly discouraged and should mostly be left to legacy.
