### ISSUE TITLE
Allow using HTTP method as a predicate

### ISSUE THREAD

**Issue by sandinmyjoints** [jefflau/jest-fetch-mock#142]
The various mock-if conditionals take the url as input, but it'd be great to have a way to choose whether to mock or not based on HTTP method, for example, only mock POSTs.

**Comment by jefflau** [comment]
Is this possible to do @yinzara?

**Comment by yinzara** [comment]
Absolutely.  They also accept a function that accepts a http.Request and returns a boolean of true or false.  

`fetch.doMockIf(req => req.method === "POST")`

**Comment by jefflau** [comment]
Maybe we can add this as an example!

**Comment by yinzara** [comment]
It already is. See Readme.md :)
