### ISSUE TITLE
Promise .finally not working

### ISSUE THREAD

**Issue by EthanML** [jefflau/jest-fetch-mock#151]
When attempting to test code that uses `.finally` on a Promise chain I get the following error:

```
TypeError: fetch(...).then(...).then(...).catch(...).finally is not a function
```

Code in question:

```javascript
fetch(myUrl)
      .then(response => {
        if (response.status === 200) {
          return response.json()
        }
        throw new Error('request failed.');
      })
      .then(({ data }) => doStuff(data))
      .catch(e => { setError(e.message) })
      .finally(() => doOtherStuff());
```

The test makes use of the following fetch mocking function:

```javascript
fetchMock.mockResponseOnce(JSON.stringify(myResponseBody));
```

I came across https://github.com/jefflau/jest-fetch-mock/pull/58 which appeared to be intended to fix exactly this issue, so I'm confused why this is happening for me.  Does anyone know why I'd still be seeing this error given the fix in that PR?

**Comment by jefflau** [comment]
Just looking at this now. I went and checked the PR and I checked the current package.json

Seems to be all there, so not sure  why it wouldn't work

**Comment by jefflau** [comment]
@EthanML Did it work for you in the end?

**Comment by EthanML** [comment]
@jefflau It didn't, I just ended up with an implementation that didn't use `finally` 😅

**Comment by gusa4grr** [comment]
@EthanML it can be related to NodeJS version. If you're using lover that 10, `finally` keyword is not supported there and it will throw error
