### ISSUE TITLE
Assert request made to the correct url

### ISSUE THREAD

**Issue by keithjgrant** [jefflau/jest-fetch-mock#18]
I need to assert that my fetch() is sent to the correct url. Is there a way to see an array of requests handled by jest-fetch-mock?

**Comment by keithjgrant** [comment]
Digging into the source, I now realize that `fetch` is a regular Jest mock, with everything that comes with it. So this assertion works:

```
expect(fetch).toBeCalledWith('http://example.com');
```

Perhaps this should be called out more clearly in the documentation.

**Comment by jefflau** [comment]
Yes you are right. Feel free to create PR to help with the documentation for your use case.

Thanks!

**Comment by jefflau** [comment]
Documentation has been updated to better explain this.

Thanks for the feedback!
