### ISSUE TITLE
"ReferenceError: self is not defined" in all test suites

### ISSUE THREAD

**Issue by mthmulders** [jefflau/jest-fetch-mock#2]
Using Jest 15.1.1, I'm trying to add jest-fetch-mock to my project. I've added a setupJestFetchMock.js file with just `global.fetch = require('jest-fetch-mock')` in it, and referenced this file from my Jest configuration. I didn't set `automock` to `false` since that's the default since Jest 15.

All my test suites now fail with

      ● Test suite failed to run

        ReferenceError: self is not defined
      
          at Object.<anonymous> (node_modules/jest-fetch-mock/src/index.js:11:28)
          at Object.<anonymous> (setupJestFetchMock.js:1:683)

This seems a bit odd to me, the instructions for setting up weren't that hard and yet I manage to get some strange error. Did I make a mistake somewhere?

**Comment by jefflau** [comment]
Hey @mthmulders. Can you paste me some of your test code and the functions they are testing?

**Comment by jefflau** [comment]
I've published a new version of `jest-fetch-mock`. Can you see if this fixes the issue?

**Comment by mthmulders** [comment]
Hi @jefflau, the removal of `self` does the trick. My tests are running again. Thanks!

They didn't even use your library - yet. I just installed it and wanted to try it out but didn't get that far. I'll try to build a test and see if it runs OK.

**Comment by mthmulders** [comment]
Yep, tests seem to run by now. Thanks again!

**Comment by jefflau** [comment]
Great to hear! You're welcome!

Sent from my iPhone

On Sep 30, 2016, at 10:12 PM, Maarten Mulders <notifications@github.com<mailto:notifications@github.com>> wrote:


Yep, tests seem to run by now. Thanks again!

-
