### ISSUE TITLE
fetch hangs with latest version of jest 27.0.4

### ISSUE THREAD

**Issue by timt** [jefflau/jest-fetch-mock#204]
"jest": "^26.6.3",
    "jest-fetch-mock": "^3.0.3",

Specifying in jest.config.js:
      global.fetch = require('jest-fetch-mock');

Call to fetch(...) hang and never return, e.g. no invocation of .then or .catch happening.

**Comment by yinzara** [comment]
I think you're configuration isn't correct.  Can you please reread the library setup instructions in the README?
