### ISSUE TITLE
Security vulnerability through dependency to cross-fetch > node-fetch

### ISSUE THREAD

**Issue by Highbrainer** [jefflau/jest-fetch-mock#227]
See https://github.com/advisories/GHSA-r683-j2x4-v87g
Upgrading the version of cross-fetch to the latest (3.1.5 by the timing of writing) fixes the problem.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/2913749/151434428-e6a63a45-b988-4531-ae5d-317270983653.png">

**Comment by diogopaulino** [comment]
Hey Guys!

Any news on this?

Could you update the lib like the potential @Highbrainer suggested?

**Comment by shivam-agarwalla-medly** [comment]
Hey Guys

Please update cross-fetch version >= 3.1.5

Thanks
