### ISSUE TITLE
First argument to fetch should be allowed to be any stringifiable

### ISSUE THREAD

**Issue by DougReeder** [jefflau/jest-fetch-mock#234]
[fetch](https://developer.mozilla.org/en-US/docs/Web/API/fetch) allows the first argument to be a Request or "A string or any other object with a [stringifier](https://developer.mozilla.org/en-US/docs/Glossary/Stringifier) — including a [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) object — that provides the URL of the resource you want to fetch."

If the first argument to fetch is not a string or Request, but does have a .toString() method, that should be called, instead of throwing the error "Unable to parse input as string or Request"

**Comment by DougReeder** [comment]
Ah, there hasn't been a release in two years.  May I suggest it's time to publish version 3.0.4 to NPM?

**Comment by blissdev** [comment]
Just noting that I ran into this as well, has it been released?

**Comment by arumsey** [comment]
https://github.com/jefflau/jest-fetch-mock/pull/193

**Comment by DougReeder** [comment]
Indeed it is.  What can be done to get a new release out?
