### ISSUE TITLE
Response, Headers, Request undefined

### ISSUE THREAD

**Issue by jhalborg** [jefflau/jest-fetch-mock#24]
As mentioned in comment on `84c4f69 `, I get undefined for these values on master branch - but if I use 

`const { Response, Headers, Request } = require('whatwg-fetch');`

instead of 

`require('whatwg-fetch');`

it works.

**Comment by joeybaker** [comment]
FWIW, I setup a fork that fixes this problem but has a slightly different setup API. I'd be happy to PR that if @jefflau wants, but it would be a breaking change: https://github.com/scriptdash/jest-fetch-mock

Here's the important bit: https://github.com/scriptdash/jest-fetch-mock/commit/86ba5ab67c0f40871e4079f95bc3bc3d4a8b4b94

**Comment by jefflau** [comment]
Should work now with `isomorphic-fetch` instead of `what-wg`
