### ISSUE TITLE
ES5 examples

### ISSUE THREAD

**Issue by john-doherty** [jefflau/jest-fetch-mock#25]
I'd like to use this but I don't understand how it works from the readme. What's wrong with writing plain old, clear ES5 examples? 

Removes the need for users to have to get their head around ES6 syntax before then trying to understand your lib.

Just my 2c ;)

**Comment by jefflau** [comment]
Nothing wrong with it. I just don't use ES5 anymore so it would be hard for me to write the docs for it! 

I will be extending the examples to non-redux and non-es6 soon so it's a bit more accessible. When I first wrote this it was just to scratch my own itch and I had a particular use case that I copied over to the examples.

**Comment by jefflau** [comment]
I have added documentation for a simple example. It does not use redux, it still uses `() =>` arrow functions but the rest is not ES6 applicable. Closing for now. You can reopen if there are other issues
