### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by TimoSta** [jefflau/jest-fetch-mock#28]
I was looking into using this library for one of our applications, but couldn't find a license explicitly specified. Now IANAL, but it [seems like a legal hazard ](https://choosealicense.com/no-license/) to use this library productively.

@jefflau, would you mind adding a license to the repo, so that we can use the code for testing our applications?

I would appreciate it a lot!

**Comment by jefflau** [comment]
Sorry for the late reply. Ill get on this!

**Comment by jefflau** [comment]
I've added an MIT license
