### ISSUE TITLE
depends on isomorphic-fetch instead of whatwg based one

### ISSUE THREAD

**Issue by phra** [jefflau/jest-fetch-mock#31]
it's possibile to support both nodejs and browser envs if you are depending on [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch) instead of the [WHATWG based one](https://github.com/github/fetch).

**Comment by phra** [comment]
@jefflau any updates? otherwise i have to fork your repo with this changes and publish it separately.

**Comment by jefflau** [comment]
Sorry for the delay. Ive commented on your PR

**Comment by phra** [comment]
done. you can merge the PR. :)

**Comment by phra** [comment]
@jefflau you should bump the version as MINOR and ship it on npm. :shipit:

**Comment by jefflau** [comment]
Sorry about that. Done.

**Comment by phra** [comment]
@jefflau sorry but there is a typo in my PR and now the npm package is not working. i've already sent a PR to fix it and you should merge and ship it ASAP. :ship:
