### ISSUE TITLE
allow to inject argument for Promise.reject() into mockReject and mockRejectOnce

### ISSUE THREAD

**Issue by akleiber** [jefflau/jest-fetch-mock#33]
While using `mockReject()` or `mockRejectOnce()` it could be practical to allow to define the reason of the rejection. Currently both methods just do a `Promise.reject()` without any argument.

Scenario:

```
function collect (data, callback) {
  fetch('someUrl', init)
   .catch((error) => {
     callback(error)
   })
}

const callback = (error, response) => {
  //do something on error
}
collect({some: 'data'}, callback)
```
What I think would be nice to have: 

```
test('test if callback is getting called with error argument', (done) => {
  fetch.mockRejectOnce(new Error('boom'))
  const callback = function (error) {
    expect(error).toEqual(expect.any(Error))
    done()
  }
 collect({}, callback)
})
```

If this is something you would support I will create a PR.

**Comment by jefflau** [comment]
Paging @hally9k who implemented this initial reject mocks.

**Comment by AllenFang** [comment]
any progress here? I think I can open a PR for this if necessary :)

**Comment by brettpostin** [comment]
I'm trying to use this in conjunction with [`redux-api-middleware`](https://github.com/agraboso/redux-api-middleware). 

`mockReject()` causes e.message to fail as the error is undefined. I suspect the above PR would help solve that but would it also be possible to return an empty Error object if not defined?

**Comment by AllenFang** [comment]
above PR is just allow to pass any data to `mockReject` and resolve it from promise. so you can pass anything by yourself.

**Comment by jefflau** [comment]
Merged and published to NPM.
