### ISSUE TITLE
typo in isomoprhic-fetch require

### ISSUE THREAD

**Issue by phra** [jefflau/jest-fetch-mock#36]
the library is requiring `isomoprhic-fetch` instead of `isomorphic-fetch`

**Comment by mrceperka** [comment]
@phra Oh, great, you've created a PR. You've been faster. I will close mine (https://github.com/jefflau/jest-fetch-mock/pull/38).

Let's hope it will be merged soon.

**Comment by phra** [comment]
@mrceperka :smile: 
let's wait for @jefflau !

**Comment by jefflau** [comment]
merged and published in 1.3.3
