### ISSUE TITLE
Mocking headers

### ISSUE THREAD

**Issue by bschlenk** [jefflau/jest-fetch-mock#41]
Is there a good way to mock the headers that are returned with a response? I have a module that checks the content-type returned, but I'm having a hard time testing because I can't actually set the content-type header of the mocked response.

**Comment by jefflau** [comment]
I haven't used it this way, so I'm not 100%, but you should be able to set the Header as part of the Response init as jest fetch mock uses the Response Object of the Fetch API.

https://developer.mozilla.org/en-US/docs/Web/API/Response/Response

**Comment by villelahdenvuo** [comment]
I was able to fetch headers just fine: `fetch.mockResponseOnce('{ "id": 1 }', { status: 200, headers: { 'content-type': 'application/json' } });`

**Comment by bschlenk** [comment]
Thanks @villelahdenvuo, that works!

**Comment by viveknandhangelella** [comment]
> I was able to mock the headers just fine: `fetch.mockResponseOnce('{ "id": 1 }', { status: 200, headers: { 'content-type': 'application/json' } });`

how to mock the response.ok value

**Comment by jefflau** [comment]
I think by default `ok === true` as it uses the response object. https://developer.mozilla.org/en-US/docs/Web/API/Response

But you can try adding `okay: true` in the object and that should work too

**Comment by draco** [comment]
@viveknandhangelella you shouldn't need to set the `ok` directly, it should take effect based on the `status` you set.

`fetch.mockResponseOnce('Simple Text', { status: 300, headers: { 'content-type': 'text/plain; charset=UTF-8'} });`should return `response.ok` as `false`.

**Comment by viveknandhangelella** [comment]
thank you @draco, it worked

**Comment by viT-1** [comment]
Can't catch error =(

fetchData has code:
```
const resp = await fetch(`/someUrl/?search=${params.label}`);
if (!resp.ok)
	throw new Error(resp.statusText);
```

test:
```
expect.assertions(1);
const statusText = 'Shit happens!';
fetchMock.mockResponseOnce('fail', {
	headers: { 'content-type': 'text/plain; charset=UTF-8' },
	status: 401,
	statusText,
});

expect(() => {
	PointSvc.fetchData({ label: 'anysearch' });
})
	.toThrow(statusText);
```

`Received function did not throw`

**Comment by villelahdenvuo** [comment]
@viT-1 Your code is wrong, the correct way to catch a rejected promise is: `await expect(my Promise).rejects.toThrow();`

**Comment by viT-1** [comment]
@villelahdenvuo Thank you very much!
