### ISSUE TITLE
Options in package.json Jest configuration not supported by Create React App

### ISSUE THREAD

**Issue by PetrFila** [jefflau/jest-fetch-mock#42]
Tried using https://www.npmjs.com/package/jest-fetch-mock, but when we add the following to package.json, it gives error `These options in your package.json Jest configuration are not currently supported by Create React App: automock, and setupFiles
```,
  "jest": {
    "automock": false,
    "setupFiles": [
      "./setupJest.js"
    ]
  }
```
How else can we approach setting the Jest configuration to use jest-fetch-mock?

**Comment by jefflau** [comment]
Just did a quick search. Looks like CRA automatically includes the setupFile called `setupTests.js`, you could try that name instead and see if it works

https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#initializing-test-environment

**Comment by jefflau** [comment]
Looks like automock is defaulted to false as well so you might be able to exclude it from the package.json

https://facebook.github.io/jest/docs/en/configuration.html#automock-boolean

**Comment by jefflau** [comment]
@PetrFila Let me know how you sorted it out

**Comment by PetrFila** [comment]
@jefflau Hi Jeff, sorry for a late reply. We were trying to make it work with my colleague but we couldn't figure it out so we gave up and never tried again since we had to move on. Thanks for your reply anyway.
