### ISSUE TITLE
response lacks blob()

### ISSUE THREAD

**Issue by ben-freenome** [jefflau/jest-fetch-mock#45]
When using jest-fetch-mock with Jest 22:
`fetch.mockResponseOnce(new Blob());` returns a response, but `response.blob()` fails with `TypeError: response.blob is not a function`. Setting appropriate headers seems to have no effect. Is this an issue with jest-fetch-mock or my own tests?
Thanks!

**Comment by ben-freenome** [comment]
on further inspection the issue seems to have popped up somewhere between v1.2.1 and v1.4.0. Perhaps something to do with dependencies swapping out?

**Comment by jefflau** [comment]
I just tried it with 1.4 in a fresh install of `create-react-app` and I can't replicate the error. 

```js
    fetch.mockResponseOnce(new Blob());
    APIRequest().then(res => {
      console.log(res.blob());
    });
```

Am I replicating the error in the way you are doing it?

**Comment by ben-freenome** [comment]
that was what I was doing; I'll see if I can still replicate the error on my end.

**Comment by ben-freenome** [comment]
hm, running your above code with 1.4 or 1.5 still throws `TypeError: res.blob is not a function`; it may be some peculiar interaction with another library I'm running. Either way, it looks like v1.4 swapped out one of jest-fetch-mock's libraries, which I'm thinking is where this issue cropped up for me.

**Comment by coremessage** [comment]
It looks like this is because `jest-fetch-mock` uses `isomorphic-fetch`, which has not been updated in a long time, and uses a really old version of `node-fetch`, which indeed lacks `blob()`. It's not clear to me why everything works on some setups, and doesn't work on other (this needs further investigation).

Why, though, are you using `isomorphic-fetch`? Jest is node-only anyway...

**Comment by nryoung** [comment]
I am running in to this as well. Is there a reason `isomorphic-fetch` is being used instead of something newer? If not I can look at doing a PR to update this.

**Comment by jefflau** [comment]
There is a PR. But i want to make sure it doesn’t break the package for anyone as it is a large change
