### ISSUE TITLE
support for node-fetch ? 

### ISSUE THREAD

**Issue by alfonsodev** [jefflau/jest-fetch-mock#5]
Hi, I couldn't make this package work on nodejs to mock 'node-fetch' package.
Could you give me some directions so that I can contribute to make this package work for nodejs too ?
Thanks!

**[updates]** 
I found this configuration works with nodejs 
package.json

```
"jset": {
    "testEnvironment": "node",
```

```
//setupJest.js
import fetch from 'jest-fetch-mock'
jest.setMock('node-fetch', fetch)
```

The problem now is that `Request` and `Response` are not present in `nodejs`
I think it could be cool if this package could read jest configuration, 
then if testEnvironment == node , use Request and Response polyfills/mocks

**Comment by kwelch** [comment]
I was able to get this working with my steps I mentioned in [this comment](https://github.com/jefflau/jest-fetch-mock/issues/9#issuecomment-277810467)

**Comment by jefflau** [comment]
Should be working now with `isomorphic-fetch`. Originally was written for the browser.
