### ISSUE TITLE
jest-fetch-mock being over ridden by actual fetch package

### ISSUE THREAD

**Issue by paultannenbaum** [jefflau/jest-fetch-mock#51]
Hi there, I am having an issue with implementing the library, and wondering what the best way to tackle the issue is.

So in my redux project, we have an `api` file that makes service calls to our backend service, using `isomorphic-fetch`. This file imports the module and then invokes fetch on the given service urls.

I believe I have my test file setup correctly, the `fetch` object is the `jest-fetch-mock` object (has access to the mock methods, etc.) when the test starts up, but when the test passes through the `api` file it is using the `fetch` object from the `isomorphic-fetch` module instead of the mock module. Because I am importing `isomorphic-fetch` module directly into the file, it is over riding the global fetch object I set in the `setupTests` file. I have confirmed this by removing the import from the api file, and then the test will use the mock fetch object that was set as a global in the setup file.

So my question is what is wrong about my implementation? Any help would be appreciated.

**Comment by paultannenbaum** [comment]
Would still a love a response on this. For now I am getting passed this by doing a check at the package level.

```
//api.js
import isoFetch from 'isomorphic-fetch'

const fetch = global.fetch || isofetch
...
```

Def less than ideal to have this check, but seems to be the only way I can get my tests to use the mock library right now.

**Comment by paultannenbaum** [comment]
So I figured out this myself, and wanted to post my solution in case anyone else is a bonehead like me. Isomorphic fetch sets fetch as a global regardless of evironment. So no need to name the import.

Before my import in api.js looked like this:
`import fetch from 'isomorphic-fetch`

Now it looks like this:
`import isomorphic-fetch`

Everything else stays the same 🙌

**Comment by jefflau** [comment]
Glad you sorted it out!

________________________________

**Comment by ryexley** [comment]
I'd like to publicly thank @paultannenbaum for sharing his solution that he discovered. I didn't fully understand what my problem was, but I was experiencing the exact same issue. I wasted 5 hours worth of work yesterday trying to figure out why this wasn't working as documented, and then I stumbled on to this issue, and my problem was solved instantly. Thanks so much for sharing.
