### ISSUE TITLE
Promise suggestion

### ISSUE THREAD

**Issue by AllenFang** [jefflau/jest-fetch-mock#54]
Hey @jefflau 

### Preface
About [`Promise.finally`](https://github.com/tc39/proposal-promise-finally) is already going to stage 4, some promise library already support `finally` function.

### Issue
Recently, I used `finally` with `fetch` in my code, everything is work well, but when I writing the test leverage by `jest-fetch-mock`, there's something wrong. Anyway, the modern browser's fetch already support finally except for Edge. you can try it easily on browser dev tool

### Root cause
I think due to `jest-fetch-mock` still use native Promise so that some people will got above issue.

Do you consider to use [`promise-polyfill`](https://github.com/taylorhakes/promise-polyfill) to fix this issue?, it's already support [`finally`](https://github.com/taylorhakes/promise-polyfill/pull/72)

Probably, I can try to fix this issue by a PR after your confirmation

**Comment by jefflau** [comment]
I'm open to this. Could you show me how you would implement it?

**Comment by jefflau** [comment]
Sounds good!
