### ISSUE TITLE
Can no longer flush promises since 1.6.0

### ISSUE THREAD

**Issue by doug-wade** [jefflau/jest-fetch-mock#66]
I have some tests where I want to await the outcome of the results of fetch requests.  The tests look like this

```
const manipulateDom = async () => {
    const wrapper = mount(<Provider store={store}><MyContainer /></Provider>);
    wrapper.find('button').simulate('click');
    await () => new Promise(resolve => setImmediate(resolve));
    return wrapper;
};
it('handles failures', async () => {
        fetch.mockReject(new Error('The request failed!'));

        const wrapper = await manipulateDom();

        expect(wrapper.find('results').html()).toContain('Failed to send contacts with error: {0}');
});
```

Note that I'm testing logic that does _not_ return the promise, so I can't await it directly.  Instead, I rely on the fact that the mock will resolve on next tick, and await `setImmediate` to wait for the next tick before making my assertions.  This worked great, but it seems that the new Promise polyfill introduced in [this PR](https://github.com/jefflau/jest-fetch-mock/commit/b0bcac9fe69ef566279b309a352c735c3c8a962b) has broken this behavior (afaict, since it _also_ uses `setImmediate` as well, we can no longer be certain that has been resolved before our setImmediate.  I'm a little hazy on the detail, though, as I haven't spelunked very far into the implementations of the promise polyfill).

**Comment by nerfologist** [comment]
After upgrading to 1.6.0, I'm getting a bunch of `Possible Unhandled Promise Rejection: { Error: expect(received).toBe(expected)` in my Jest test suite too. I believe it's connected to the problem described by @doug-wade.

**Comment by jefflau** [comment]
I'm going to merge this immediately and publish. Can you check if it works after?

**Comment by nerfologist** [comment]
@jefflau sure I'll test it first thing in the morning (CET). Thanks for your support 👍

**Comment by doug-wade** [comment]
hi there @jefflau!  We got this updated today, and our CI build is happily passing.  Thanks so much for your quick response!
