### ISSUE TITLE
First example does not work as expected

### ISSUE THREAD

**Issue by JacobFrericks** [jefflau/jest-fetch-mock#69]
I'm talking about the "simple mock and assert" example. I copied the api.js and api.test.js exactly. I'll paste them here for reference

```
//api.js
export function APIRequest(who) {
  if (who === 'google') {
    return fetch('https://google.com').then(res => res.json())
  } else {
    return 'no argument provided'
  }
}
```
```
//api.test.js
import { APIRequest } from './api'

describe('testing api', () => {
  beforeEach(() => {
    fetch.resetMocks()
  })

  it('calls google and returns data to me', () => {
    fetch.mockResponseOnce(JSON.stringify({ data: '12345' }))

    //assert on the response
    APIRequest('google').then(res => {
      expect(res.data).toEqual('12345')
    })

    //assert on the times called and arguments given to fetch
    expect(fetch.mock.calls.length).toEqual(1)
    expect(fetch.mock.calls[0][0]).toEqual('https://google.com')
  })
})
```

I tried changing each "expect" to verify the test fails. The last two work perfectly, it verified that https://google.com was called exactly once.

The first expect (inside the APIRequest) does not fail when I change it to 'abcde'. I put a console log right above the expect to make sure it's actually being run, and it printed no problem. I put another console log underneath the expect, and that is NOT being printed. 

```
        APIRequest('google').then(res => {
            console.log("Before: " + res.data); // prints "Before: 12345"
            expect(res.data).toEqual('abcde')
            console.log("After: " + res.data); // Does not print
        })
```

Why would this be happening? I'm running v1.6.2, Windows 10.

**Comment by jefflau** [comment]
That's a bit confusing. Can you create a repo and I'll have a look?

**Comment by JacobFrericks** [comment]
Sorry for the delay, here is the repository: https://github.com/JacobFrericks/jest-temp/

Basically I used the "create-react-native-app" tool, then added the api.js and api.test.js from the examples and pasted them in. I changed [one line](https://github.com/JacobFrericks/jest-temp/blob/master/api.test.js#L14) in the test, expecting it to fail, but it still passes.

**Comment by IanVS** [comment]
I believe you need to use the `done` callback to let jest know when the test is finished, like so:

```
//api.test.js
import { APIRequest } from './api'

describe('testing api', () => {
  beforeEach(() => {
    fetch.resetMocks()
  })

  it('calls google and returns data to me', (done) => {
    fetch.mockResponseOnce(JSON.stringify({ data: '12345' }))

    //assert on the response
    APIRequest('google').then(res => {
      expect(res.data).toEqual('12345')
	  done()
    })

    //assert on the times called and arguments given to fetch
    expect(fetch.mock.calls.length).toEqual(1)
    expect(fetch.mock.calls[0][0]).toEqual('https://google.com')
  })
})
```

**Comment by JacobFrericks** [comment]
I tried that, and it does indeed do what I want! All the tests fail when they should, and pass when they should. However, there is one weird thing.

If I change the last two expects to fail, say by changing the last one to be
```
expect(fetch.mock.calls[0][0]).toEqual('https://thisShouldFail.com')
```
I get the expected error:
```
Error: expect(received).toEqual(expected)

Expected value to equal:
  "https://thisShouldFail.com"
Received:
  "https://google.com"
```

However, if I change the first expect to be this:
```
expect(res.data).toEqual('67890')
```
I get an unexpected error:
```
Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
```

I expected something like "Expected value to equal: 12345 Received: 67890". Why did I get this other error?

Thank you for helping with this!

**Comment by JacobFrericks** [comment]
I updated my repository with the issue. If you run the test, you get the Async error.

https://github.com/JacobFrericks/jest-temp/

**Comment by linconkusunoki** [comment]
@JacobFrericks any update? I'm having the same problems

**Comment by tjmabey** [comment]
I was having the same issue with the first example. I got it to work by adding `return` in front of the assert based on reading the [Jest docs on promises](https://github.com/jefflau/jest-fetch-mock#mocking-a-failed-fetch). 

> Be sure to return the promise - if you omit this return statement, your test will complete before fetchData completes.

Docs should definitely be updated, because it can be very frustrating when one can't even get the most basic example to work correctly.

**Comment by toklok** [comment]
Glad I came across this, here was my solution

```
import { APIRequest } from './../src/api'

describe('testing api', () => {
    beforeEach(() => {
        fetch.resetMocks()
    })

    it('calls google and returns data to me', async () => {
        expect.assertions(3);
        fetch.mockResponseOnce(JSON.stringify({ data: '12345' }))

        const res = await APIRequest('google');
        //assert on the response
        expect(res.data).toEqual('12345');

        //assert on the times called and arguments given to fetch
        expect(fetch.mock.calls.length).toEqual(1);
        expect(fetch.mock.calls[0][0]).toEqual('https://google.com');
    })
})
```

**Comment by gotofritz** [comment]
Made a PR to add @toklok's fix to the README
