### ISSUE TITLE
mockResponse should take a function as argument, whose result can be used as response

### ISSUE THREAD

**Issue by tiger9502** [jefflau/jest-fetch-mock#77]
this is to enable mocking a delayed response.

maybe even consider adding a second argument in mockResponse as response time in ms.

**Comment by jefflau** [comment]
Can you write up some pseudo code to explain what you mean? Why do you need the delayed response?

**Comment by tiger9502** [comment]
sure...
let's say you do fetch.mockResponse(JSON.stringify('my server is really slow'), 500)
to mock a slow server that takes 500 ms to respond

**Comment by jefflau** [comment]
Apart from an edge case of slow servers - you'd probably want to mock most responses so they are fast so I'm uneasy changing the simpler API. Maybe it could be a new method as opposed to changing the current API. Something like fetch.mockDelayedResponse?

What would the Pseudo code look like if you used a function as an argument instead?

**Comment by tiger9502** [comment]
it can be used to mock a simple webserver.

something like this:
fetch.mockResponse((username, email) => JSON.stringify({ message: `Welcome,
${username}! Your email is ${email}` }));

**Comment by jefflau** [comment]
have you seen this PR by @isimone?

https://github.com/jefflau/jest-fetch-mock/pull/75

Would this kind of implementation be similar to what you were suggestion?

**Comment by Julien-Decoen** [comment]
Hi @tiger9502, @jefflau !
Is this issue has been resolved ?

Thanks

**Comment by franciscop** [comment]
Is this or #75 going to move forward, @jefflau and @lsimone? This library is perfect, but this is blocking me as well. Is there a way I can help somehow?

**Comment by lsimone** [comment]
I want to provide the new PR but I didn't have time so far.
I'll try to find it in the next 2 weeks!

**Comment by tomevans18** [comment]
Is there any update on this?
From my usage this is the last piece of the puzzle.

**Comment by jefflau** [comment]
I'd love to get this in, but I'm also a little busy these days. The discussion on this implementation is over here: https://github.com/jefflau/jest-fetch-mock/pull/75 and I think the general use case of either taking an object or a promise is a decent generalised API which would enable async support.

@lsimone is there any chance you will get some time to implement what we discussed back in June?

**Comment by lsimone** [comment]
@jefflau I'll try to deliver it this Sunday (or before if I can)

**Comment by tomevans18** [comment]
Legend!

**Comment by jefflau** [comment]
This is now merged and published. Please take a look and test it out for us! I will close this issue soon after

**Comment by tomevans18** [comment]
@lsimone epic work!
@jefflau thanks for the update 👍 

I will start using this and feedback any issues.

**Comment by jefflau** [comment]
@tomevans18 Working smoothly so far?

**Comment by jefflau** [comment]
Closing this issue. Assuming everything is working fine :)

**Comment by Shelagh-Lewins** [comment]
In case it helps someone else, here's how I used this feature to mock two calls with a delay. Note that you need to advance the timers for each mock separately:

In your file:

    const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
    jest.useFakeTimers();

In your test:

      fetchMock
        .mockResponseOnce(async () => {
          await delay(1000); // 1 second delay
          return {
            body: JSON.stringify(mockResponse1),
            status: 200,
          };
        })
        .mockResponseOnce(async () => {
          await delay(2000); // 2 seconds delay
          return {
            body: JSON.stringify(mockResponse2),
            status: 200,
          };
        });

      // do the render

      // Advance timers to allow the first fetch to complete
      await act(async () => {
        jest.advanceTimersByTime(1000);
      });

      // Advance timers to allow the second fetch to complete
      await act(async () => {
        jest.advanceTimersByTime(2000);
      });

**Comment by roar-skinderviken** [comment]
Thanks @Shelagh-Lewins. I took your suggestion a little bit further.

```
import {MockResponseInit} from "jest-fetch-mock"

const delayedResponse = (
    body: string,
    delayInMillis: number,
    status: number = 200) =>

    new Promise<MockResponseInit>(resolve =>
        setTimeout(
            () => resolve({body, status}),
            delayInMillis)
    )
```

Usage in tests:
```
fetchMock.mockResponseOnce(async () => 
    await delayedResponse(JSON.stringify({foo: "bar"}, 100))
```
