### ISSUE TITLE
mock responses that are not ok

### ISSUE THREAD

**Issue by michaelknoch** [jefflau/jest-fetch-mock#86]
I did not realy get how to mock a realistic fetch failing behaviour. [As described in this article](https://www.tjvantoll.com/2015/09/13/fetch-and-errors/) fetch only rejects promises if network errors happen. So for example if the server returns a `500`, fetch normally would resolve a promise with `{response: { ok: false }}`.

Is it possible to mock such a response?
```js
fetch.mockResponse({ ok: false });
```
does not seem to work as expected

**Comment by jefflau** [comment]
When you say it does not seem to work as expected - what happens?

jest-fetch-mock allows you pass a Response object, so whatever you usually get in that you should be able to mock.

https://developer.mozilla.org/en-US/docs/Web/API/Response

**Comment by michaelknoch** [comment]
it was my bad @jefflau, i havent seen the second parameter
```js
fetch.mockResponseOnce(JSON.stringify("fail"), { status: 401, ok: false });
```

**Comment by dustwise** [comment]
This does not work for me.

`fetch.once(JSON.stringify('testdata'), {ok: false});`

results in:

> Argument of type '{ok: boolean;}' is not assignable to parameter of type 'MockParams'. Object literal may only specify known properties, and 'ok' does not exist in type 'MockParams';

Thoughts?

**Comment by joel-s** [comment]
This works for me; apparently `ok` gets set to `false` based on the status code.
```js
    fetchMock.mockResponseOnce(
      JSON.stringify('Ignore this'),
      { status: 500, statusText: 'Server error' },
    );
```
