### ISSUE TITLE
ActualResponse is not a constructor

### ISSUE THREAD

**Issue by Kepro** [jefflau/jest-fetch-mock#9]
in my test 
````
import React from 'react';
import { mount } from 'enzyme';
import Help from './Help';

describe('Help basic functionality', () => {
  it('should be able to show help', () => {
   fetch.mockResponse(JSON.stringify({access_token: '12345' }));
    fetch.mockResponseOnce(JSON.stringify({ name: 'naruto' }));
 
    const wrapper = mount(
      <Help content="transformation_test" />,
    );

    expect(wrapper.html()).toBe('<div class="help"><span>Increment</span></div>');
  });
});
````
but i getting

    TypeError: ActualResponse is not a constructor
      
      at new ResponseWrapper (node_modules/jest-fetch-mock/src/index.js:33:10)
      at fetch.mockImplementationOnce (node_modules/jest-fetch-mock/src/index.js:48:27)
      at Help.loadContent (app/components/help/Help.jsx:46:14)

I have " global.fetch = require('jest-fetch-mock'); " 

and in Help I just calling window.fetch

**Comment by Kepro** [comment]
if i use 

````
const mockResponse = (status, statusText, response) => {
  return new window.Response(response, {
    status: status,
    statusText: statusText,
    headers: {
      'Content-type': 'application/json'
    }
  });
};

window.fetch = jest.fn().mockImplementation(() => Promise.resolve(mockResponse(
    400, 'Test Error', '{"status":400, "statusText": Test Error!}')));
````

this is working

**Comment by blech75** [comment]
i get the same error using the latest 1.0.7 version.

if i revert to 1.0.5, which does not include the change in #8, the `ActualResponse is not a constructor ` problem goes away.

**Comment by Kepro** [comment]
yep, 1.0.5 it's working correctly

**Comment by okeydoke** [comment]
yeah I just ran in to this, went back to `1.0.6` which works for me

**Comment by kwelch** [comment]
I have gotten this issue when running with `test-environment` of `jsdom` which is default. 

I was able to fix it, by importing `isomorphic-fetch` before inside of my file that was references from `setupTestFrameworkScriptFile` in my jest config.

**Comment by techniq** [comment]
I was having this issue as well and ended up going with [fetch-mock](https://github.com/wheresrhys/fetch-mock) and so far it plays well within jest for my [react-fetch-component](https://github.com/techniq/react-fetch-component/blob/master/src/Fetch.test.js) component.

**Comment by Scarysize** [comment]
I got the same issue, breaks my tests. Jest v 17.0.3.

**Comment by jefflau** [comment]
I've reverted the previous pull request in 1.0.8

**Comment by Scarysize** [comment]
Great! Thank you.

**Comment by Kepro** [comment]
thanks!

**Comment by amahrt** [comment]
+1 any solution for this?

**Comment by Scarysize** [comment]
@amahrt The error was reverted AFAIK, this shouldn't be an issue anymore if you are using `^1.0.8`

**Comment by amahrt** [comment]
@Scarysize I'm using `^1.1.1` 

```
     ● ApiService › fires a request

    TypeError: ActualResponse is not a constructor
      
      at new ResponseWrapper (node_modules/jest-fetch-mock/src/index.js:33:10)
      at fetch.mockImplementation (node_modules/jest-fetch-mock/src/index.js:42:27)
      at ApiRequest.execute (modules/app/services/api/ApiRequest.js:80:13)
      at ApiService._work (modules/app/services/ApiService.js:222:9)
      at Object._callee$ (__tests__/modules/app/services/ApiService.spec.js:77:12)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)

  ApiService
    ✕ fires a request (2ms)
    ○ skipped 3 tests
