### ISSUE TITLE
SyntaxError: Unexpected token <<

### ISSUE THREAD

**Issue by prymitive** [jefflau/jest-fetch-mock#91]
Looks like index.js code includes a left over line from a merge conflict
https://github.com/jefflau/jest-fetch-mock/blob/master/src/index.js#L1
and because of that latest release doesn't work - https://travis-ci.com/prymitive/karma/jobs/157582009#L488

**Comment by jefflau** [comment]
Thanks, I fixed that too

**Comment by smoliakov** [comment]
Yes, works fine for me, thanks!

**Comment by reorg3** [comment]
Thanks. Do you also plan to add the yarn.lock file? @jefflau

**Comment by prymitive** [comment]
Looks good now, thanks

**Comment by alexaivars** [comment]
Might be a good idea to mark the 1.7.0 version as deprecated on npm. Our greenkeeper tried to install this and I guess marking it as deprecated would just make tools like this skip that version.

**Comment by jefflau** [comment]
Thanks, I've done that now
